export enum Report {
    EACH_TEST_SUITE_RUNS = 'EVERY_TIME_TEST_SUITE_RUNS',
    DAILY_REPORTS = 'DAILY_REPORTS',
    WEEKLY_REPORTS = 'WEEKLY_REPORTS',
    MONTHLY_REPORTS = 'MONTHLY_REPORTS',
    EVENT_NOTIFICATIONS = 'EVENT_NOTIFICATIONS'
}