
name: Code linting

on:
  pull_request:
     branches: [ main ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install Angular dependencies
        run: |
          cd ./ui
          npm install --legacy-peer-deps
      
      - name: Run Linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_dir: ./ui