name: Continuous testing in Integration

on:
  schedule:
    - cron: '0 */2 * * *'

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run API tests
      id: run-newman
      uses: matt-ball/newman-action@master
      with:
        collection: ./tests/api/postman/LicenseServerAPIs.postman_collection.json
        environment: ./tests/api/postman/LicenseServerAPIsEnv.postman_environment.json
        reporters: '["junit", "cli"]'
        reporter: "{ \"junit\": { \"export\": \"./tests/api/postman/newman-report.xml\" } }"

    - name: Publish JUnit Report
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: './tests/api/postman/newman-report.xml'
        summary: 'true'
        check_name: 'API Test Report'
    
    - name: Set Integration test credentials
      run: |
        echo -e "\nusername=${{ secrets.AZURE_TEST_USER_NAME }}" >> ./tests/ui/src/main/resources/integration.properties
        echo -e "password=${{ secrets.AZURE_TEST_USER_PWD }}" >> ./tests/ui/src/main/resources/integration.properties

    - name: Run UI tests
      run: |
        cd tests/ui
        gradle uiTests -Denv=integration
    - uses: deblockt/cucumber-report-annotations-action@v1.7
      name: Publish Cucumber Report
      with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber.json"