# Workflow to build and deploy to Azure cloud the License Server UI  

name: License Server CI/CD

# Controls when the workflow will run
on:
#   workflow_dispatch:
  # Triggers the workflow on push to main branch
  push:
    branches: [ main ]
  # or pull request events but only for the main branch
  # pull_request:
  #   branches: [ main ]

env:
  AZURE_FUNCTIONAPP_NAME: tekvLicenseServerPOCFunction
  POM_XML_DIRECTORY: 'azure-functions/'
  POM_FUNCTIONAPP_NAME: myFunction-12345
  JAVA_VERSION: '1.8.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_LICENSE_SERVER_CREDENTIALS }}
     
    - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}

    - name: 'Restore Project Dependencies Using Mvn'
      shell: bash
      run: |
        pushd './${{ env.POM_XML_DIRECTORY }}'
        mvn clean package -Dmaven.test.skip -Dexec.skip -q
        mvn azure-functions:package
        popd

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    
    - name: Get Commit Short Hash
      id: hash
      run: echo "::set-output name=hash::$(git rev-parse --short "$GITHUB_SHA")"
    
    - name: Archive Azure Functions Build
      uses: vimtor/action-zip@v1
      with:
        files: './${{ env.POM_XML_DIRECTORY }}/target/azure-functions/'
        recursive: true
        dest: 'af-release-${{steps.date.outputs.date}}.zip'

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './${{ env.POM_XML_DIRECTORY }}/target/azure-functions/${{ env.POM_FUNCTIONAPP_NAME }}'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: Use Node.js 12.20
      uses: actions/setup-node@v1
      with:
        node-version: '12.20'
    
    - name: Build Angular Production web app
      run: |
        cd ./ui
        npm install
        npm run build:prod
        
    - name: Archive UI Production Build
      uses: vimtor/action-zip@v1
      with:
        files: './ui/dist/'
        recursive: true
        dest: 'ui-prod-release-${{steps.date.outputs.date}}.zip'

    - name: Build Angular Integration web app
      run: |
        cd ./ui
        npm install
        npm run build
    
    - name: Archive UI Integration Build
      uses: vimtor/action-zip@v1
      with:
        files: './ui/dist/'
        recursive: true        
        dest: 'ui-integration-release-${{steps.date.outputs.date}}.zip'

    - name: Upload to blob storagerun
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az storage blob upload-batch --overwrite --account-name lswebappstorage --auth-mode key -d '$web' -s ./ui/dist
           
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
          # az cdn endpoint purge --content-paths  "/*" --profile-name "CDN_PROFILE_NAME" --name "CDN_ENDPOINT" --resource-group "RESOURCE_GROUP"
        
    - name: 'Run API tests'
      run: |
        ls
        npm install -g newman
        newman run ./tests/api/postman/LicenseServerAPIs.postman_collection.json -e ./tests/api/postman/LicenseServerAPIsEnv.postman_environment.json
    
    - name: Archive Full Build
      uses: vimtor/action-zip@v1
      with:
        files: 'af-release-${{steps.date.outputs.date}}.zip ui-integration-release-${{steps.date.outputs.date}}.zip ui-prod-release-${{steps.date.outputs.date}}.zip'
        recursive: true        
        dest: 'LS-release-${{github.run_number}}-${{steps.date.outputs.date}}-${{steps.hash.outputs.hash}}.zip'
    
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ github.event.head_commit.message }}
        artifacts: 'LS-release-${{github.run_number}}-${{steps.date.outputs.date}}-${{steps.hash.outputs.hash}}.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Print Release Version
      run: echo 'Released ${{ steps.tag_version.outputs.new_tag }} Build'
    
  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
  # Debug (ssh into running host)
  #  - name: Debug on failure
  #    if: failure()
  #    uses: mxschmitt/action-tmate@v3
