# Workflow to build and deploy to Azure cloud the License Server UI  

name: License Server CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_LICENSE_SERVER_CREDENTIALS }}
          
    - name: Use Node.js 13.10
      uses: actions/setup-node@v1
      with:
        node-version: '13.10'
        
    - name: Build Angular web app
      run: |
        cd ./ui
        npm install
        npm run build -- "--base-href=/license-server/ --configuration production"
        # ng build --base-href='/license-server/' --configuration production
        
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az storage blob upload-batch --account-name lswebappstorage --auth-mode key -d '$web' -s ./dist
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
          # az cdn endpoint purge --content-paths  "/*" --profile-name "CDN_PROFILE_NAME" --name "CDN_ENDPOINT" --resource-group "RESOURCE_GROUP"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
  # Debug (ssh into running host)
  #  - name: Debug on failure
  #    if: failure()
  #    uses: mxschmitt/action-tmate@v3
