# Workflow to acquire release and deploy to Azure cloud the License Server components

name: Push Release

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version'
        required: true
        default: 'latest'
env:
  AZURE_FUNCTIONAPP_NAME: tekvizion-portal
  POM_FUNCTIONAPP_NAME: myFunction-12345

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_PRODUCTION_LICENSE_SERVER_CREDENTIALS }}
        - name: Install Zip
          uses: montudor/action-zip@v1
        
        - name: Retrieve release assets
          id: release_download
          uses: dsaltares/fetch-gh-release-asset@master
          with:
            version: '${{ github.event.inputs.release_version }}'
            regex: true
            file: "LS"
            target: "./"

        - name: Unzip Release Folder
          run: unzip -qq *.zip -d Release

        - name: Unzip Production UI
          run: unzip -qq ui-prod-release*.zip -d UI-prod-build
          working-directory: Release
        
        - name: Add Release version file
          run: echo "Released ${{ steps.release_download.outputs.version }} Build" > ./Release/UI-prod-build/license-server/ReleaseVersion.txt

        - name: Upload to blob storagerun
          uses: azure/CLI@v1
          with:
            inlineScript: |
              az storage blob upload-batch --overwrite --account-name tekvizionportal --auth-mode key -d '$web' -s ./Release/UI-prod-build
        
        - name: Unzip Azure Functions UI
          run: unzip -qq af-release*.zip -d Azure-functions
          working-directory: Release
        
        - name: 'Run Azure Functions Action'
          uses: Azure/functions-action@v1
          id: fa
          with:
            app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
            package: './Release/Azure-functions/${{ env.POM_FUNCTIONAPP_NAME }}'
            publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_PRODUCTION }}
        
        - name: Print deployed Release Version
          run: echo 'Released ${{ steps.release_download.outputs.version }} Build'
          
        - name: logout
          run: az logout
          if: always()